name: Run pre-commit hooks
on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install pre-commit==4.2.0

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
